feat: add Belgian eID support
web-eid/libelectronic-id pull request #31
Opened 2022-06-02 12:18 UTC by matsjoonas

Refs: https://github.com/web-eid/libelectronic-id/issues/30

Now I'm not sure whether you accept pull requests or not from third-party collaborators (feel free to just close it, if not), but I'm hoping that this PR has at least some informational value and serves as a good starting point for when you start implementing the Belgian eID.

Please note that:
https://github.com/web-eid/libelectronic-id/compare/main...eideasy:main#diff-1d1e9d13402083e3e4cfef76240e0afa5c7dbd2c004dbd19153acbe3703be28dL169-L175

https://github.com/web-eid/libelectronic-id/compare/main...eideasy:main#diff-5e815893cc922d5085482de88a00dc7775fb3201555be4efaa224115aebb80dbL41-R50

^ I changed these parts to explicitly check for the signing certificate. The reason for this is that the Belgian eID card has 4 certs so we can't assume that if the cert is not for authentication then it must always be for signing. In this specific case, the old code threw at the Root CA cert at enums.hpp  `if (value == NONE)` check and caused the whole program to abort. However, for Root CA cert it makse sense to have a value of NONE, since it is neither a signing nor authentication cert.

2022-06-03 10:50 UTC, mrts commented
@matsjoonas, heartfelt thanks! We are really happy to receive this pull requests and will review and integrate it when we start working with v2.2.0. Are comfortable with signing the Contributor License Agreement, https://ltsi.linuxfoundation.org/software/signed-off-process/?

2022-06-06 15:15 UTC, matsjoonas commented
Glad to hear that :) 

>Are you comfortable with signing the Contributor License Agreement.

Sure. no problem. I rebased my commits to include the sign-off comments. Is there anything else I need to do regarding the signing?

By the way, what's your ballpark timeline for the v2.2.0 release?

2022-06-08 08:55 UTC, mrts commented
> Sure. no problem. I rebased my commits to include the sign-off comments. Is there anything else I need to do regarding the signing?

Thank you! That is sufficient.

> By the way, what's your ballpark timeline for the v2.2.0 release?

The next larger release will be in late autumn. However, we may publish a minor less thoroughly tested release (presumably with Belgian eID support) before that.

2022-07-13 17:08 UTC, mrts requested changes
Two more gentle requests:

1. We maintain clean, linear Git history. Can you please rebase your changes on latest main, so that your merge request contains only a single, signed commit?
2. Can you please format the code with [`./scripts/clang-format.sh`](https://github.com/web-eid/libelectronic-id/blob/main/scripts/clang-format.sh)? This requires recent [`clang-format`](https://clang.llvm.org/docs/ClangFormat.html) in system path. We use it in Linux and macOS, but it should work in Windows as well from a Git Bash shell.

2022-07-18 11:06 UTC, matsjoonas commented on src/electronic-ids/pkcs11/Pkcs11ElectronicID.cpp
> +
I agree, makes sense. I'll change this according to your recommendation.

2022-07-19 13:14 UTC, mrts commented on src/electronic-ids/pkcs11/Pkcs11ElectronicID.cpp
> +
Thank you, looks good to me now!

2022-07-19 13:38 UTC, merged